"""add_ocr_and_full_text_search_fields

Revision ID: 14765318ba03
Revises: 4e2f12cbfd94
Create Date: 2025-11-02 11:07:22.322034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14765318ba03'
down_revision: Union[str, None] = '4e2f12cbfd94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('ocr_text', sa.Text(), nullable=True))
    op.add_column('photos', sa.Column('ocr_confidence', sa.Float(), nullable=True))
    op.add_column('photos', sa.Column('ocr_metadata', sa.JSON(), nullable=True))
    op.add_column('photos', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_photos_search_vector', 'photos', ['search_vector'], unique=False, postgresql_using='gin')

    # TSVector自動更新トリガー作成（simple設定を使用）
    op.execute("""
        CREATE OR REPLACE FUNCTION photos_search_vector_update() RETURNS trigger AS $$
        BEGIN
            NEW.search_vector :=
                setweight(to_tsvector('simple', coalesce(NEW.file_name, '')), 'A') ||
                setweight(to_tsvector('simple', coalesce(NEW.title, '')), 'A') ||
                setweight(to_tsvector('simple', coalesce(NEW.description, '')), 'B') ||
                setweight(to_tsvector('simple', coalesce(NEW.ocr_text, '')), 'B') ||
                setweight(to_tsvector('simple', coalesce(NEW.work_type, '')), 'C') ||
                setweight(to_tsvector('simple', coalesce(NEW.work_kind, '')), 'C');
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER photos_search_vector_trigger
        BEFORE INSERT OR UPDATE ON photos
        FOR EACH ROW EXECUTE FUNCTION photos_search_vector_update();
    """)

    # 既存レコードのsearch_vectorを更新
    op.execute("""
        UPDATE photos SET search_vector =
            setweight(to_tsvector('simple', coalesce(file_name, '')), 'A') ||
            setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
            setweight(to_tsvector('simple', coalesce(description, '')), 'B') ||
            setweight(to_tsvector('simple', coalesce(ocr_text, '')), 'B') ||
            setweight(to_tsvector('simple', coalesce(work_type, '')), 'C') ||
            setweight(to_tsvector('simple', coalesce(work_kind, '')), 'C')
        WHERE search_vector IS NULL;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # トリガーと関数を削除
    op.execute("DROP TRIGGER IF EXISTS photos_search_vector_trigger ON photos;")
    op.execute("DROP FUNCTION IF EXISTS photos_search_vector_update();")

    op.drop_index('ix_photos_search_vector', table_name='photos', postgresql_using='gin')
    op.drop_column('photos', 'search_vector')
    op.drop_column('photos', 'ocr_metadata')
    op.drop_column('photos', 'ocr_confidence')
    op.drop_column('photos', 'ocr_text')
    # ### end Alembic commands ###
