"""add project_id to photos table

Revision ID: 242ebc892924
Revises: 6c9f69f2b32f
Create Date: 2025-11-03 19:46:07.784508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242ebc892924'
down_revision: Union[str, None] = '6c9f69f2b32f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add project_id column to photos table
    op.add_column('photos', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_photos_project_id'), 'photos', ['project_id'], unique=False)
    op.create_foreign_key(
        'fk_photos_project_id_projects',
        'photos',
        'projects',
        ['project_id'],
        ['id'],
        ondelete='RESTRICT'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove project_id column from photos table
    op.drop_constraint('fk_photos_project_id_projects', 'photos', type_='foreignkey')
    op.drop_index(op.f('ix_photos_project_id'), table_name='photos')
    op.drop_column('photos', 'project_id')
    # ### end Alembic commands ###
