"""add_duplicate_detection_and_quality_fields

Revision ID: 4e2f12cbfd94
Revises: b0236f1c85bb
Create Date: 2025-11-02 10:58:04.676981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2f12cbfd94'
down_revision: Union[str, None] = 'b0236f1c85bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_duplicates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo1_id', sa.Integer(), nullable=False),
    sa.Column('photo2_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('duplicate_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['photo1_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['photo2_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_duplicates_id'), 'photo_duplicates', ['id'], unique=False)
    op.create_index(op.f('ix_photo_duplicates_photo1_id'), 'photo_duplicates', ['photo1_id'], unique=False)
    op.create_index(op.f('ix_photo_duplicates_photo2_id'), 'photo_duplicates', ['photo2_id'], unique=False)
    op.add_column('photos', sa.Column('perceptual_hash', sa.String(length=64), nullable=True))
    op.add_column('photos', sa.Column('duplicate_group_id', sa.String(length=36), nullable=True))
    op.add_column('photos', sa.Column('quality_score', sa.Integer(), nullable=True))
    op.add_column('photos', sa.Column('quality_issues', sa.JSON(), nullable=True))
    op.add_column('photos', sa.Column('is_duplicate', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_photos_duplicate_group_id'), 'photos', ['duplicate_group_id'], unique=False)
    op.create_index(op.f('ix_photos_perceptual_hash'), 'photos', ['perceptual_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_perceptual_hash'), table_name='photos')
    op.drop_index(op.f('ix_photos_duplicate_group_id'), table_name='photos')
    op.drop_column('photos', 'is_duplicate')
    op.drop_column('photos', 'quality_issues')
    op.drop_column('photos', 'quality_score')
    op.drop_column('photos', 'duplicate_group_id')
    op.drop_column('photos', 'perceptual_hash')
    op.drop_index(op.f('ix_photo_duplicates_photo2_id'), table_name='photo_duplicates')
    op.drop_index(op.f('ix_photo_duplicates_photo1_id'), table_name='photo_duplicates')
    op.drop_index(op.f('ix_photo_duplicates_id'), table_name='photo_duplicates')
    op.drop_table('photo_duplicates')
    # ### end Alembic commands ###
