"""make_project_id_required_in_photos

Revision ID: d63a04ae57a0
Revises: 242ebc892924
Create Date: 2025-11-03 20:24:40.806969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63a04ae57a0'
down_revision: Union[str, None] = '242ebc892924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 既存のNULLレコードを処理するため、各organizationにデフォルトプロジェクトを作成
    # 1. photosテーブルにproject_idがNULLのレコードがあるorganizationを取得
    conn = op.get_bind()

    # project_idがNULLの写真を持つ組織を取得
    result = conn.execute(
        sa.text("""
            SELECT DISTINCT organization_id
            FROM photos
            WHERE project_id IS NULL
        """)
    )
    org_ids = [row[0] for row in result]

    # 各組織にデフォルトプロジェクトを作成
    for org_id in org_ids:
        # デフォルトプロジェクトが既に存在するか確認
        existing = conn.execute(
            sa.text("""
                SELECT id FROM projects
                WHERE organization_id = :org_id
                AND name = 'デフォルトプロジェクト'
            """),
            {"org_id": org_id}
        ).fetchone()

        if existing:
            default_project_id = existing[0]
        else:
            # デフォルトプロジェクトを作成
            result = conn.execute(
                sa.text("""
                    INSERT INTO projects (organization_id, name, description, status, created_at, updated_at)
                    VALUES (:org_id, 'デフォルトプロジェクト', '既存写真用の自動生成プロジェクト', 'active', NOW(), NOW())
                    RETURNING id
                """),
                {"org_id": org_id}
            )
            default_project_id = result.fetchone()[0]

        # project_idがNULLの写真にデフォルトプロジェクトを割り当て
        conn.execute(
            sa.text("""
                UPDATE photos
                SET project_id = :project_id
                WHERE organization_id = :org_id AND project_id IS NULL
            """),
            {"project_id": default_project_id, "org_id": org_id}
        )

    # project_idをNOT NULLに変更
    op.alter_column('photos', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
